version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  format: github-actions

linters:
  enable:
    - revive
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - unparam
    - misspell
    - errorlint
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/bmf-san/ggc

  misspell:
    locale: US

  gocritic:
    enabled-checks:
      # Style
      - ifElseChain
      - boolExprSimplify
      - commentedOutCode
      - emptyStringTest
      - underef

      # Performance
      - hugeParam
      - rangeValCopy
      - sloppyLen
      - appendAssign

      # Bug detection
      - badCond
      - dupBranchBody
      - nilValReturn
      - offBy1

  unparam:
    check-exported: false

  revive:
    rules:
      # Documentation
      - name: exported
      - name: package-comments

      # Code quality
      - name: unused-parameter
      - name: var-naming
      - name: function-result-limit
        arguments: [3]
      - name: argument-limit
        arguments: [5]
      - name: cyclomatic
        arguments: [10]

      # Error handling
      - name: error-return
      - name: error-strings
      - name: error-naming

      # Best practices
      - name: context-as-argument
      - name: empty-block
      - name: superfluous-else

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Relax rules for test files
    - path: _test\.go
      linters:
        - revive
        - gocritic

skip-files:
  - ".*_mock\\.go"
  - ".*\\.pb\\.go"
  - "testdata/.*"
